[terrain]
EMPTY = 0x00
BLANK = 0x01
STONE_UL = 0x02
STONE_UC = 0x03
STONE_UR = 0x04
STONE_ML = 0x05
STONE_MR = 0x06
STONE_BL = 0x07
STONE_BC = 0x08
STONE_BR = 0x09
GRASS_UL = 0x0a
GRASS_UC = 0x0b
GRASS_UR = 0x0c
GRASS_ML = 0x0d
GRASS_MC = 0x0e
GRASS_MR = 0x0f
GRASS_BL = 0x10
GRASS_BC = 0x11
GRASS_BR = 0x12
GRASS_FLOAT_END_L = 0x13
GRASS_FLOAT_END_R = 0x14
WOOD_UL = 0x15
WOOD_UC = 0x16
WOOD_UR = 0x17
WOOD_ML = 0x18
WOOD_MR = 0x19
WOOD_BL = 0x1a
WOOD_BC = 0x1b
WOOD_BR = 0x1c
MOSS_UL = 0x1d
MOSS_UC = 0x1e
MOSS_UR = 0x1f
MOSS_ML = 0x20
MOSS_MR = 0x21
MOSS_BL = 0x22
MOSS_BC = 0x23
MOSS_BR = 0x24
PINK_GRASS_UL = 0x25
PINK_GRASS_UC = 0x26
PINK_GRASS_UR = 0x27
PINK_GRASS_ML = 0x28
PINK_GRASS_MC = 0x29
PINK_GRASS_MR = 0x2a
PINK_GRASS_BL = 0x2b
PINK_GRASS_BC = 0x2c
PINK_GRASS_BR = 0x2d
PINK_GRASS_FLOAT_END_L = 0x2e
PINK_GRASS_FLOAT_END_R = 0x2f
HOR_BRASS_L = 0x30
HOR_BRASS_C = 0x31
HOR_BRASS_R = 0x32
VER_BRASS_U = 0x33
VER_BRASS_M = 0x34
VER_BRASS_B = 0x35
BRASS_SINGLE = 0x36
BRASS_BIG_UL = 0x37
BRASS_BIG_UR = 0x38
BRASS_BIG_BL = 0x39
BRASS_BIG_BR = 0x3a
HOR_METAL_L = 0x3b
HOR_METAL_C = 0x3c
HOR_METAL_R = 0x3d
VER_METAL_U = 0x3e
VER_METAL_M = 0x3f
VER_METAL_B = 0x40
METAL_SINGLE = 0x41
METAL_BIG_UL = 0x42
METAL_BIG_UR = 0x43
METAL_BIG_BL = 0x44
METAL_BIG_BR = 0x45
WOOD_END_UL = 0x46
WOOD_END_UR = 0x47
WOOD_END_BL = 0x48
WOOD_END_BR = 0x49
STONE_END_UL = 0x4a
STONE_END_UR = 0x4b
STONE_END_BL = 0x4c
STONE_END_BR = 0x4d
MOSS_END_UL = 0x4e
MOSS_END_UR = 0x4f
MOSS_END_BL = 0x50
MOSS_END_BR = 0x51

# start at 112
[traps]
TRAP1=0x70
TRAP2=0x71
TRAP3=0x72
TRAP4=0x73
TRAP5=0x74
TRAP6=0x75
TRAP7=0x76
TRAP8=0x77
TRAP9=0x78

# start at 128
[platforms]
PLATFORM1=0x80
PLATFORM2=0x81
PLATFORM3=0x82
PLATFORM4=0x83
PLATFORM5=0x84
PLATFORM6=0x85
PLATFORM7=0x86
PLATFORM8=0x87
PLATFORM9=0x88

# start at 176 (max 16 characters)
[characters]
CHARACTER = 0xb0
ENEMY1 = 0xb1 # mush
ENEMY2 = 0xb2 # trunk
ENEMY3 = 0xb3 # bee
ENEMY4 = 0xb4
ENEMY5 = 0xb5
ENEMY6 = 0xb6
ENEMY7 = 0xb7
ENEMY8 = 0xb8
ENEMY9 = 0xb8

# start at 192 (max 64 pickups)
[pickups]
APPLE = 0xc0
BANANA = 0xc1
CHERRY = 0xc2
KIWI = 0xc3
MELON = 0xc4
ORANGE = 0xc5
PINEAPPLE = 0xc6
STRAWBERRY = 0xc7
